# Generated by Django 4.1 on 2022-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
